### ISSUE TITLE
'data_preprocessed/train_data_sample_gray.p 'where is this file?

### ISSUE THREAD

**Issue by liuyang1273** [DoDuy/Lung-Diseases-Classifier#1]

**Comment by DoDuy** [comment]
I will take the time to update the readme in the next few days,
Your problem can be solved by running the file https://github.com/DoDuy/Lung-Diseases-Classifier/blob/master/Data%20preprocessing%20-%20SampleDataset.ipynb to create the file data_preprocessed / train_data_sample_gray.p...
You need download dataset first :)

**Comment by liuyang1273** [comment]
'from utils import plot_log'  What's the use of this code?  Run out of error, ModuleNotFoundError: No module named 'utils'. After looking up the data, it is found that there is no such  module.

**Comment by aduk4u** [comment]
I solved this issue by creating the folder data_preprocessed.
