### ISSUE TITLE
question

### ISSUE THREAD

**Issue by liuyang1273** [DoDuy/Lung-Diseases-Classifier#2]
'from utils import plot_log'  What's the use of this code?  Run out of error, ModuleNotFoundError: No module named 'utils'. After looking up the data, it is found that there is no such  module. @DoDuy

**Comment by DoDuy** [comment]
I missed this file, thank you for reminding @liuyang1273 
I uploaded this file https://github.com/DoDuy/Lung-Diseases-Classifier/blob/master/utils.py
