### ISSUE TITLE
can you share this file for running demo file:  'pretrained_extradata_stn_CNN.best.from_scratch.hdf5'

### ISSUE THREAD

**Issue by mallesh797** [DoDuy/Lung-Diseases-Classifier#3]
pretrained model

**Comment by DoDuy** [comment]
@mallesh797 I'm so sorry, I haven't kept that file pretrained_extradata_stn_CNN.best.from_scratch.hdf5
Please train and save model by yourself

**Comment by mallesh797** [comment]
ok will try thank you
