### ISSUE TITLE
hi these files are also not found, request you to upload them as well,    "data_preprocessed/train_data_sample_rgb.p"    ,, "data_preprocessed/valid_data_sample_rgb.p"......, "data_preprocessed/test_data_sample_rgb.p

### ISSUE THREAD

**Issue by mallesh797** [DoDuy/Lung-Diseases-Classifier#4]
HI please add these files, i was trying to run the datapreprocessing  file, i got error based on above mentioned files.

**Comment by DoDuy** [comment]
@mallesh797 Your problem can be solved by
1. Download dataset https://www.kaggle.com/nih-chest-xrays/sample
2. Create folder 'data_preprocessed'
3. Run https://github.com/DoDuy/Lung-Diseases-Classifier/blob/master/Data%20preprocessing%20-%20SampleDataset.ipynb to create the file data_preprocessed / train_data_sample_gray.p...
